## 1. Using Numpy to invert the matrices:

$$
\mathbf{A} = 
\begin{bmatrix}
3 & -7 & 45 & 21 \\
12 & 11 & 10 & 17 \\
6 & 25 & -80 & -24 \\
17 & 55 & -9 & 7 \\
\end{bmatrix}
;
\mathbf{B} = 
\begin{bmatrix}
1 & 1 & 1 & 1 \\
1 & 2 & 2 & 2 \\
2 & 3 & 4 & 4 \\
4 & 5 & 6 & 7 \\
\end{bmatrix}
$$


In [5]:
import numpy as np

A = np.array([
    [3, -7, 45, 21], 
    [12, 11, 10, 17], 
    [6, 25, -80, -24], 
    [17, 55, -9, 7]
    ])

B = np.array([
    [1, 1, 1, 1],
    [1, 2, 2, 2],
    [2, 3, 4, 4],
    [4, 5, 6, 7]
    ])

print("Inverse of A")
np.linalg.inv(A)

Inverse of A


array([[-2.73050828e+00,  1.48528059e+00, -1.34659614e+00,
        -3.24862006e-02],
       [ 4.82405704e-01, -2.78748850e-01,  2.33210672e-01,
         2.93238270e-02],
       [-6.54036339e-01,  3.24287029e-01, -3.40616375e-01,
         6.72723091e-03],
       [ 2.00000000e+00, -1.00000000e+00,  1.00000000e+00,
        -1.11022302e-16]])

In [6]:
print("Inverse of B")
np.linalg.inv(B)

Inverse of B


array([[ 2.00000000e+00, -1.00000000e+00,  4.44089210e-16,
        -1.85037171e-16],
       [-1.48029737e-16,  2.00000000e+00, -1.00000000e+00,
         1.48029737e-16],
       [ 1.00000000e+00, -1.00000000e+00,  2.00000000e+00,
        -1.00000000e+00],
       [-2.00000000e+00, -0.00000000e+00, -1.00000000e+00,
         1.00000000e+00]])

## 2. Solve the following equations with the 3 methods in our class:

$$
\begin{bmatrix}
12 & -2 & 3 & 1 \\
-2 & 15 & 6 & -3 \\
1 & 6 & 20 & -4 \\
0 & -3 & 2 & 9 \\
\end{bmatrix}
\begin{bmatrix}
x_1 \\
x_2 \\
x_3 \\
x_4 \\
\end{bmatrix}
 = 
\begin{bmatrix}
0 \\
0 \\
20 \\
0 \\
\end{bmatrix}
$$

In [23]:
A = np.array([
    [12, -2, 3, 1],
    [-2, 15, 6, -3],
    [1, 6, 20, -4],
    [0, -3, 2, 9]])

y = np.array([0, 0, 20, 0])

### 2a. Using np.linalg.solve

In [8]:
from numpy.linalg import solve

solve(A, y)

array([-0.33439845, -0.57219291,  1.10128558, -0.4354611 ])

### 2b. Using np.linalg.inv and np.linalg.dot

In [12]:
from numpy.linalg import inv, det

A_inv = inv(A)

A_det = det(A)

if A_det != 0:
    print(np.dot(A_inv, y))

26914.000000000025
[-0.33439845 -0.57219291  1.10128558 -0.4354611 ]


### 2c. Using row reduction

In [51]:
#  Obtain the augmented matrix
augmented_matrix = np.concatenate((A, y.reshape(4, 1)), axis=1)

# Turning first element in row 2 to 0
augmented_matrix[1] = augmented_matrix[0] + 6 * augmented_matrix[1]

# Turning first element in row 3 to 0
augmented_matrix[2] = augmented_matrix[0] + (-12) * augmented_matrix[2]

# Turning second element in row 3 to 0
augmented_matrix[2] = 37 * augmented_matrix[1] + 44 * augmented_matrix[2]

# Turning second element in row 4 to 0
augmented_matrix[3] = 3 * augmented_matrix[1] + 88 * augmented_matrix[3]

# Turning third element in row 4 to 0
augmented_matrix[3] = 293 * augmented_matrix[2] + 8985 * augmented_matrix[3]

# x4 
x4 = augmented_matrix[3, 4] / augmented_matrix[3, 3]

# x3
x3 = (augmented_matrix[2, 4] - x4 * augmented_matrix[2, 3]) / augmented_matrix[2, 2]

# x2
x2 = (augmented_matrix[1, 4] - x3 * augmented_matrix[1, 2] - x4 * augmented_matrix[1, 3]) / augmented_matrix[1, 1]

# x1
x1 = (augmented_matrix[0, 4] - x2 * augmented_matrix[0, 1] - x3 * augmented_matrix[0, 2] - x4 * augmented_matrix[0, 3]) / augmented_matrix[0, 0]

solution = np.array([x1, x2, x3, x4])

print(solution)

[-0.33439845 -0.57219291  1.10128558 -0.4354611 ]


## 3. Write a function calc_similarity(s1,s2) where s1 and s2 are strings (may have different size). From s1 and s2, the function should construct two vectors, v1 and v2, where v1[0] is the number of a’s in s1, v1[1] is the number b’s in s1, and so on until v1[25], which is the number of z’s in v1. The vector v2 should be similarly constructed from s2. The output should be cos(θ).

In [67]:
def calc_similarity(s1, s2):
    v1 = np.zeros((25,), dtype=int)
    v2 = np.zeros((25,), dtype=int)

    for c in s1.lower().replace(" ", ""):
        v1[ord(c) - ord("a")] += 1

    for c in s2.lower().replace(" ", ""):
        v2[ord(c) - ord("a")] += 1

    return v1.dot(v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

s1 = "Write a function calcsimilaritys where s and s"
s2 = "number of as in s v is the number bs in s and s"

print(calc_similarity(s1, s2))

0.7756992985103194
